name: api_com_msql_ibge
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mysql1: ^0.19.2

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0




